### PR TITLE
Use ENTRYPOINT to execute docker image

### LINKED ISSUE #33: Use ENTRYPOINT to execute docker image

### PR DESCRIPTION
**Pull request by rootwarp**
close #33

### CODE REVIEW

**Comment by rootwarp** [comment]
@kim201212 I'm testing on M1 and Intel server but it takes too long time.

**Review by kim201212 — APPROVED** [review]
LGTM

**Comment by kim201212** [comment]
> @kim201212 I'm testing on M1 and Intel server but it takes too long time.

Is it a problem to contribute KZG ceremony?

**Comment by kim201212** [comment]
It takes a too long time. Can't contribute using docker.

**Pull request closed without merging**
